class IdentitySuite < Formula
  desc "IdentitySuite CLI and API tools"
  homepage "https://github.com/neon-covenant/identity-suite"
  url "https://github.com/neon-covenant/identity-suite/archive/refs/tags/v1.0.0.tar.gz"
  sha256 "<AUTOGENERATED_SHA256>"
  license "MIT"

  depends_on "perl"

  def install
    bin.install "cli.pl"
  end

  test do
    system "#{bin}/cli.pl", "--version"
  end
end
